name: Adrenotools to Discord

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "$(jq -n --arg name "${{ github.event.release.name }}" \
                      --arg url "${{ github.event.release.html_url }}" \
                      --arg body "${{ github.event.release.body }}" \
                      '{
                        content: "<@&1429870971296284832>",
                        embeds: [{
                          title: "New Release: \($name)",
                          url: $url,
                          description: $body,
                          color: 16711680,
                          footer: { text: "New Release!" }
                        }],
                        allowed_mentions: {
                          roles: ["1429870971296284832"]
                        }
                      }')" \
            "$WEBHOOK_URL"
