name: Poll DXVK Workflows

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (to store last_run_id)
        uses: actions/checkout@v3

      - name: Fetch previous run ID
        id: prev
        run: |
          LAST_RUN_FILE=".last_run_id"
          if [ -f "$LAST_RUN_FILE" ]; then
            echo "last_run_id=$(cat $LAST_RUN_FILE)" >> $GITHUB_ENV
          else
            echo "last_run_id=" >> $GITHUB_ENV
          fi

      - name: Fetch recent successful workflow runs
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/doitsujin/dxvk/actions/runs?status=success&per_page=10&sort=created&direction=desc \
               > recent_runs.json

      - name: Check for new runs
        id: check
        run: |
          latest_id=$(jq -r '.workflow_runs[0].id // empty' recent_runs.json)
          LAST_ID="${{ env.last_run_id }}"
          if [ -z "$latest_id" ] || [ "$latest_id" = "$LAST_ID" ]; then
            echo "already_notified=true" >> $GITHUB_ENV
          else
            new_runs=$(jq -r --arg last_id "$LAST_ID" '.workflow_runs[] | select(.id > ($last_id|tonumber)) | .html_url' recent_runs.json)
            echo "already_notified=false" >> $GITHUB_ENV
            echo "notification_message=New DXVK workflow run(s):\n$new_runs" >> $GITHUB_ENV
            echo "$latest_id" > .last_run_id
          fi

      - name: Send Discord Notification
        if: env.already_notified == 'false'
        uses: tsickert/discord-webhook@v5.5.0
        with:
          webhook-url: ${{ secrets.DXVK_WEBHOOK }}
          content: ${{ env.notification_message }}

      - name: Commit updated last_run_id
        if: env.already_notified == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .last_run_id
          git commit -m "Update last_run_id"
          git push
