name: Poll FEX-Emu/FEX Workflows

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Manual trigger

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Cache last run ID
        uses: actions/cache@v4
        with:
          path: .cache
          key: fex-last-run-id  # Fixed key to persist across runs

      - name: Fetch recent successful workflow runs
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/FEX-Emu/FEX/actions/runs?status=success&per_page=10&sort=created&direction=desc \
            > recent_runs.json

      - name: Check for new runs and prepare notification
        id: check
        run: |
          mkdir -p .cache
          CACHE_FILE=".cache/last_run_id"
          latest_id=$(jq -r '.workflow_runs[0].id // empty' recent_runs.json)
          if [ -z "$latest_id" ]; then
            echo "No runs found"
            echo "already_notified=true" >> $GITHUB_ENV
            exit 0
          fi
          if [ ! -f "$CACHE_FILE" ]; then
            new_runs=$(jq -r '.workflow_runs[0].html_url' recent_runs.json)
            echo "already_notified=false" >> $GITHUB_ENV
            echo "$latest_id" > "$CACHE_FILE"
            echo "notification_message=New FEX-Emu/FEX workflow run(s):\n$new_runs" >> $GITHUB_ENV
          else
            last_id=$(cat "$CACHE_FILE")
            if [ "$last_id" = "$latest_id" ]; then
              echo "already_notified=true" >> $GITHUB_ENV
            else
              new_runs=$(jq -r --argjson last_id "$last_id" '.workflow_runs[] | select(.id > $last_id) | .html_url' recent_runs.json)
              echo "already_notified=false" >> $GITHUB_ENV
              echo "$latest_id" > "$CACHE_FILE"
              echo "notification_message=New FEX-Emu/FEX workflow run(s):\n$new_runs" >> $GITHUB_ENV
            fi
          fi

      - name: Send Discord Notification
        if: env.already_notified == 'false'
        uses: tsickert/discord-webhook@v5.5.0
        with:
          webhook-url: ${{ secrets.FEXEMU_WEBHOOK }}
          content: ${{ env.notification_message }}
