# This GitHub Actions workflow sends a notification to a Discord channel
# when any other workflow in the repository completes successfully.

name: Discord Success Notifier

on:
  workflow_run:
    # This specifies that the workflow runs on the completion of other workflows.
    workflows: ["*"] # Trigger for all workflows in the repository
    types:
      - completed

jobs:
  notify-on-success:
    # This job only runs if the triggering workflow was successful.
    # It also prevents the notifier workflow from triggering itself in an infinite loop.
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow.path != github.workflow_path
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Discord Notification
        # Uses a popular community action to send messages to Discord.
        uses: avast/discord-action@v1.0.0
        with:
          # The webhook URL is stored as a secret for security.
          url: ${{ secrets.FEXEMU_WEBHOOK }}
          # The message content to be sent to Discord.
          # The URL on a new line triggers Discord's native GitHub embed.
          content: |
            🎉 Workflow **${{ github.event.workflow_run.name }}** in `${{ github.repository }}` completed successfully!
            https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
