name: Poll FEX-Emu/FEX Workflows

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest successful workflow run
        id: get-run
        run: |
          response=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/FEX-Emu/FEX/actions/runs?status=success&per_page=1)

          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
          html_url=$(echo "$response" | jq -r '.workflow_runs[0].html_url')
          workflow_name=$(echo "$response" | jq -r '.workflow_runs[0].name')
          branch=$(echo "$response" | jq -r '.workflow_runs[0].head_branch')
          commit_id=$(echo "$response" | jq -r '.workflow_runs[0].head_sha' | cut -c1-7)
          commit_url=$(echo "$response" | jq -r '.workflow_runs[0].head_commit.url')
          author=$(echo "$response" | jq -r '.workflow_runs[0].head_commit.author.name')

          echo "run_id=$run_id" >> $GITHUB_ENV
          echo "html_url=$html_url" >> $GITHUB_ENV
          echo "workflow_name=$workflow_name" >> $GITHUB_ENV
          echo "branch=$branch" >> $GITHUB_ENV
          echo "commit_id=$commit_id" >> $GITHUB_ENV
          echo "commit_url=$commit_url" >> $GITHUB_ENV
          echo "author=$author" >> $GITHUB_ENV

      - name: Check if already notified
        id: check-cache
        run: |
          mkdir -p .cache
          CACHE_FILE=".cache/last_run_id"
          if [ -f "$CACHE_FILE" ] && [ "$(cat $CACHE_FILE)" = "${{ env.run_id }}" ]; then
            echo "already_notified=true" >> $GITHUB_ENV
          else
            echo "${{ env.run_id }}" > $CACHE_FILE
            echo "already_notified=false" >> $GITHUB_ENV
          fi

      - name: Cache store (so cache persists across runs)
        if: env.already_notified == 'false'
        uses: actions/cache@v4
        with:
          path: .cache
          key: last-run-${{ env.run_id }}

      - name: Send Discord Notification
        if: env.already_notified == 'false'
        uses: tsickert/discord-webhook@v5.5.0
        with:
          webhook-url: ${{ secrets.FEXEMU_WEBHOOK }}
          embed: |
            {
              "title": "✅ Workflow Succeeded",
              "description": "Workflow **${{ env.workflow_name }}** succeeded in [FEX-Emu/FEX](${{ env.html_url }}).",
              "color": 3066993,
              "fields": [
                {
                  "name": "Branch",
                  "value": "${{ env.branch }}",
                  "inline": true
                },
                {
                  "name": "Commit",
                  "value": "[${{ env.commit_id }}](${{ env.commit_url }})",
                  "inline": true
                },
                {
                  "name": "Author",
                  "value": "${{ env.author }}"
                }
              ]
            }
