name: Poll External Repo Actions

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes; adjust as needed (GitHub cron format)
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  poll-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Poll GitHub API for workflow runs
        id: poll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Optional; not needed for public repos
        run: |
          # Target repo details
          REPO_OWNER="FEX-Emu"
          REPO_NAME="FEX"
          
          # Export to GitHub env for later steps
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          
          # Fetch repo details for icon
          REPO_INFO=$(curl -s -f "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}")
          REPO_ICON=$(echo "$REPO_INFO" | jq -r '.owner.avatar_url')
          GITHUB_ICON="https://github.githubassets.com/images/modules/actions_dashboard/label_success.png"  # Default; override per status
          echo "repo_icon=$REPO_ICON" >> $GITHUB_OUTPUT
          
          # Fetch recent runs
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/runs?per_page=1&status=completed"  # Just the latest for notify
          RUNS=$(curl -s -f "$API_URL")
          
          # Check for API errors (e.g., 404 Not Found)
          if echo "$RUNS" | jq -e '.message? == "Not Found"' >/dev/null; then
            echo "Error: Repo ${REPO_OWNER}/${REPO_NAME} not found."
            exit 1
          fi
          
          # Get count and handle empty
          RUNS_COUNT=$(echo "$RUNS" | jq '.workflow_runs | length')
          if [ "$RUNS_COUNT" -gt 0 ]; then
            # Extract latest run details for embed (sanitize commit_msg for outputs)
            RUN_NAME=$(echo "$RUNS" | jq -r '.workflow_runs[0].name')
            RUN_STATUS=$(echo "$RUNS" | jq -r '.workflow_runs[0].conclusion')
            RUN_STATUS_UPPER=$(echo "$RUN_STATUS" | tr '[:lower:]' '[:upper:]')
            RUN_ACTOR=$(echo "$RUNS" | jq -r '.workflow_runs[0].actor.login')
            RUN_ACTOR_ID=$(echo "$RUNS" | jq -r '.workflow_runs[0].actor.id')
            RUN_TIME=$(echo "$RUNS" | jq -r '.workflow_runs[0].created_at')
            RUN_URL=$(echo "$RUNS" | jq -r '.workflow_runs[0].html_url')
            RUN_ID=$(echo "$RUNS" | jq -r '.workflow_runs[0].id')
            RUN_BRANCH=$(echo "$RUNS" | jq -r '.workflow_runs[0].head_branch')
            COMMIT_MSG_RAW=$(echo "$RUNS" | jq -r '.workflow_runs[0].head_commit.message // "No commit message"')
            COMMIT_MSG=$(echo "$COMMIT_MSG_RAW" | tr '\n' ' ' | sed 's/"/\\"/g' | cut -c1-200)  # Sanitize: remove newlines, escape quotes, truncate
            COMMIT_SHA=$(echo "$RUNS" | jq -r '.workflow_runs[0].head_commit.id // "No SHA"' | cut -c1-7)  # Short SHA
            COMMIT_AUTHOR=$(echo "$RUNS" | jq -r '.workflow_runs[0].head_commit.author.name // "Unknown"')
            COMMIT_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/commit/$(echo "$RUNS" | jq -r '.workflow_runs[0].head_commit.id // "No SHA"')"
            
            # Status emoji and icon
            if [ "$RUN_STATUS" = "success" ]; then
              STATUS_EMOJI="✅"
              GITHUB_ICON="https://github.githubassets.com/images/modules/actions_dashboard/label_success.png"
            else
              STATUS_EMOJI="❌"
              GITHUB_ICON="https://github.githubassets.com/images/modules/actions_dashboard/label_failure.png"
            fi
            TITLE="${RUN_NAME} · ${STATUS_EMOJI} ${RUN_STATUS_UPPER}"
            
            # Set outputs
            echo "run_name=$RUN_NAME" >> $GITHUB_OUTPUT
            echo "run_status=$RUN_STATUS_UPPER" >> $GITHUB_OUTPUT
            echo "run_actor=$RUN_ACTOR" >> $GITHUB_OUTPUT
            echo "run_actor_id=$RUN_ACTOR_ID" >> $GITHUB_OUTPUT
            echo "run_time=$RUN_TIME" >> $GITHUB_OUTPUT
            echo "run_url=$RUN_URL" >> $GITHUB_OUTPUT
            echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
            echo "run_branch=$RUN_BRANCH" >> $GITHUB_OUTPUT
            echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
            echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
            echo "commit_author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
            echo "commit_url=$COMMIT_URL" >> $GITHUB_OUTPUT
            echo "title=$TITLE" >> $GITHUB_OUTPUT
            echo "github_icon=$GITHUB_ICON" >> $GITHUB_OUTPUT
            echo "New run detected: $RUN_NAME ($RUN_STATUS) by $RUN_ACTOR."
          else
            echo "run_id=none" >> $GITHUB_OUTPUT
            echo "No completed runs found—skipping notify."
          fi

      - name: Send Rich Embed to Discord
        if: steps.poll.outputs.run_id != 'none'
        env:
          WEBHOOK_URL: ${{ secrets.FEXEMU_WEBHOOK }}
        run: |
          # Determine color
          COLOR=3447003  # Default blue
          if [ "${{ steps.poll.outputs.run_status }}" = "SUCCESS" ]; then
            COLOR=65280  # Green
          elif [ "${{ steps.poll.outputs.run_status }}" = "FAILURE" ]; then
            COLOR=16711680  # Red
          fi
          
          # Build embed with jq for proper escaping
          EMBED_JSON=$(jq -n \
            --arg username "GitHub Actions" \
            --argjson color "$COLOR" \
            --arg title "${{ steps.poll.outputs.title }}" \
            --arg description "${{ steps.poll.outputs.commit_msg }}" \
            --arg branch "${{ steps.poll.outputs.run_branch }}" \
            --arg sha "${{ steps.poll.outputs.commit_sha }}" \
            --arg commit_url "${{ steps.poll.outputs.commit_url }}" \
            --arg actor "${{ steps.poll.outputs.run_actor }}" \
            --arg run_url "${{ steps.poll.outputs.run_url }}" \
            --arg repo_icon "${{ steps.poll.outputs.repo_icon }}" \
            --arg actor_id "${{ steps.poll.outputs.run_actor_id }}" \
            --arg github_icon "${{ steps.poll.outputs.github_icon }}" \
            '{
              username: $username,
              avatar_url: "https://github.githubassets.com/images/modules/actions_dashboard/inverted-ghost.png",
              embeds: [{
                author: {
                  name: "FEX-Emu / FEX",
                  icon_url: $repo_icon,
                  url: "https://github.com/FEX-Emu/FEX"
                },
                title: $title,
                description: $description,
                url: $run_url,
                color: $color,
                fields: [
                  {
                    name: "Branch",
                    value: $branch,
                    inline: true
                  },
                  {
                    name: "Commit",
                    value: "[`$( $sha )` | $commit_url]",
                    inline: true
                  },
                  {
                    name: "Triggered by",
                    value: $actor,
                    inline: true
                  }
                ],
                footer: {
                  text: "GitHub Actions • All checks have passed",
                  icon_url: $github_icon
                },
                timestamp: "2025-10-04T00:00:00Z"  # Use actual run_time if formatted as ISO
              }]
            }')
          
          # Send via curl
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$EMBED_JSON" \
               "$WEBHOOK_URL"
          
          echo "Embed sent successfully!"
