name: Adrenotools to Discord

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "<@&1429870971296284832>",
              "embeds": [{
                "title": "New Release: ${{ github.event.release.name }}",
                "url": "${{ github.event.release.html_url }}",
                "description": "${{ github.event.release.body }}",
                "color": 16711680,
                "footer": { "text": "New Release!" }
              }],
              "allowed_mentions": {
                "roles": ["1429870971296284832"]
              }
            }' \
            $WEBHOOK_URL
